### ISSUE TITLE
circular_buffer.c fill check and style

### ISSUE THREAD

**Issue by esromneb** [embeddedartistry/embedded-resources#19]
# Fill check
circular_buffer does not check for full during circular_buf_put() resulting in incorrect behavior

# Style
circular_buf_full, circular_buf_empty take the full object as an argument, not the pointer, this results in large stack copies

**Comment by phillipjohnston** [comment]
Thank you for reporting this. I fixed the `circular_buf_full` and `circular_buf_empty` portion. Regarding incorrect behavior on put - I typically utilize this logic in my implementation. I have created a second example function which returns an error if the buffer is full.

**Comment by esromneb** [comment]
Thanks for the quick patches :)
