### ISSUE TITLE
Dispatch Queue race condition with destructor

### ISSUE THREAD

**Issue by lakinsm** [embeddedartistry/embedded-resources#21]
https://github.com/embeddedartistry/embedded-resources/blob/b38155a9798839db8760f003004fe8fe0b25fab9/examples/cpp/dispatch.cpp#L106

Thanks for your great examples and resources.  I am implementing a dispatch queue based on your example code.  In this particular line (106), including the quit_ variable in the conditional statement causes a race condition with the destructor, so the threads sometimes join and end execution while the queue is still populated. Removing the quit_ from this conditional statement appears to solve the problem:

`if(q_.size()):`

As opposed to the current conditional:

`if(!quit_ && q_.size())`

Hopefully this isn't just on my end somewhere, but I thought you might want to know.

**Comment by phillipjohnston** [comment]
Hey Steven,

Thanks for writing in. The behavior you describe seems to be the behavior I actually intended: if the thread receives a quit signal, we need to kill the thread ASAP, even if there is work remaining in the queue.

I don't see a problem changing this behavior, but in my particular application these threads are only destructed on exit - and work definitely doesn't need to keep going at that point.

**Comment by phillipjohnston** [comment]
Closing this, please feel free to reopen to discuss further if you think my explanation does not make sense.
